export const GET_STICKINGS = "GET_STICKINGS";
export const START_EXERCISE = "START_EXERCISE";
export const PREVIOUS_EXERCISE = "PREVIOUS_EXERCISE";
export const NEXT_EXERCISE = "NEXT_EXERCISE";
export const RANDOM_EXERCISE = "RANDOM_EXERCISE";
export const RANDOM_SBC_EXERCISE = "RANDOM_SBC_EXERCISE";
export const RANDOM_FLAM_EXERCISE = "RANDOM_FLAM_EXERCISE";
export const INVERT_EXERCISE = "INVERT_EXERCISE";
export const SEARCH_EXERCISE = "SEARCH_EXERCISE";
export const CHANGE_EXERCISE = "CHANGE_EXERCISE";

export const REGISTER_USER = "REGISTER_USER";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
